"""
Rebuild CHAT_INDEX.md against the CURRENT nested layout (post _reorganize.py).

Walks:
  tier1_deep/            NN__name__slug/
  tier2_core/            NN__name__slug/
  tier3_extended/        NNN__name__slug/
  untiered_personal/     NNN__name__slug/
  tier4_groups/active/   name__slug/
  tier4_groups/lurker/   name__slug/
  other_lid/             name__slug/

For each dir, extracts the trailing `_wa_*` slug from the folder name,
joins with per-chat stats from _triage.json, and writes CHAT_INDEX.md
grouped by physical tier bucket (not by score-only categorization).

No re-analysis of messages.json — stats already computed in _triage.json.
Fast, deterministic, mirrors what's actually on disk.

Run:  python3 _chat_index_rebuild.py
"""

import json
import re
from pathlib import Path
from collections import defaultdict

BASE = Path(__file__).parent
OUT = BASE / "CHAT_INDEX.md"

TIER_DIRS = [
    ("tier1_deep", BASE / "tier1_deep", "Tier 1 — Deep dive (top 10 personal 1:1)"),
    ("tier2_core", BASE / "tier2_core", "Tier 2 — Core corpus (ranks 11-40)"),
    ("tier3_extended", BASE / "tier3_extended", "Tier 3 — Extended (ranks 41-100)"),
    ("untiered_personal", BASE / "untiered_personal", "Untiered personal (rank 101+)"),
    (
        "tier4_groups_active",
        BASE / "tier4_groups" / "active",
        "Tier 4a — Groups (active, Ivan participates)",
    ),
    (
        "tier4_groups_lurker",
        BASE / "tier4_groups" / "lurker",
        "Tier 4b — Groups (lurker, passive-observation)",
    ),
    ("other_lid", BASE / "other_lid", "Other — LID chats not in tiers"),
]

SLUG_RE = re.compile(r"(_wa_(?:chat|group|lid|other|other_newsletter)_.+)$")


def extract_slug(folder_name: str) -> str | None:
    m = SLUG_RE.search(folder_name)
    return m.group(1) if m else None


def parse_display_name(folder_name: str) -> str:
    # NN__name__slug  or  name__slug
    if "__" not in folder_name:
        return folder_name
    parts = folder_name.split("__")
    # last part is slug; drop it. Anything else (with optional leading rank) is the name.
    if len(parts) == 2:
        return parts[0]
    # rank prefix + name + slug: parts = [rank, name, slug] (slug may contain "__" from resolve_name; guard by SLUG_RE)
    slug = extract_slug(folder_name)
    if slug:
        prefix = folder_name[: -len(slug)].rstrip("_")
        # prefix is "NN__name" or "name"
        pp = prefix.split("__", 1)
        return pp[1] if len(pp) == 2 and pp[0].isdigit() else prefix
    return parts[0]


def parse_rank(folder_name: str) -> int | None:
    m = re.match(r"^(\d+)__", folder_name)
    return int(m.group(1)) if m else None


def fmt_stats(c: dict) -> str:
    return (
        f"{c['total_msgs']:,} msgs · "
        f"{c['from_me_ratio']*100:.0f}% mine · "
        f"{c['my_text_chars']:,} my chars · "
        f"{c['audio_msgs']:,} audio · "
        f"{c['span_days']:.0f}d span · "
        f"score {c['score']:,.0f}"
    )


def main():
    triage = json.loads((BASE / "_triage.json").read_text())
    stats_by_slug = {c["slug"]: c for c in triage["chats"]}

    buckets: dict[str, list[dict]] = defaultdict(list)
    orphan_dirs: list[str] = []
    missing_stats: list[str] = []

    for key, path, _title in TIER_DIRS:
        if not path.is_dir():
            continue
        for d in sorted(path.iterdir()):
            if not d.is_dir():
                continue
            slug = extract_slug(d.name)
            if slug is None:
                orphan_dirs.append(str(d.relative_to(BASE)))
                continue
            stats = stats_by_slug.get(slug)
            if stats is None:
                missing_stats.append(slug)
                continue
            buckets[key].append(
                {
                    "folder": d.name,
                    "rel_path": str(d.relative_to(BASE)),
                    "display_name": parse_display_name(d.name),
                    "rank": parse_rank(d.name),
                    "slug": slug,
                    "stats": stats,
                }
            )

    # sort inside each bucket
    for key, rows in buckets.items():
        if key in ("tier1_deep", "tier2_core", "tier3_extended", "untiered_personal"):
            rows.sort(key=lambda r: (r["rank"] if r["rank"] is not None else 9999, r["folder"]))
        else:
            rows.sort(key=lambda r: -r["stats"]["score"])

    lines: list[str] = []
    lines.append("# WhatsApp corpus — chat index (nested layout)")
    lines.append("")
    lines.append(
        "Generated by `_chat_index_rebuild.py` — reflects the physical folder layout on disk "
        "after `_reorganize.py` and `_drop_extra_groups.py` ran. Reversible via `_rename_manifest.json`."
    )
    lines.append("")

    total = sum(len(rows) for rows in buckets.values())
    lines.append(f"**Total kept dirs on disk:** {total}")
    lines.append("")
    lines.append("| Bucket | Count |")
    lines.append("|---|---|")
    for key, _p, title in TIER_DIRS:
        lines.append(f"| {title} | {len(buckets.get(key, []))} |")
    lines.append("")

    for key, _p, title in TIER_DIRS:
        rows = buckets.get(key, [])
        if not rows:
            continue
        lines.append(f"## {title}")
        lines.append("")
        for r in rows:
            rank_prefix = f"**{r['rank']:>3}.** " if r["rank"] is not None else "- "
            lines.append(f"{rank_prefix}**{r['display_name']}**")
            lines.append(f"    - path: `{r['rel_path']}`")
            lines.append(f"    - slug: `{r['slug']}`")
            lines.append(f"    - {fmt_stats(r['stats'])}")
        lines.append("")

    if orphan_dirs:
        lines.append("## Orphan dirs (no slug parsed)")
        lines.append("")
        for o in orphan_dirs:
            lines.append(f"- `{o}`")
        lines.append("")

    if missing_stats:
        lines.append("## Missing stats (slug not in _triage.json)")
        lines.append("")
        for s in missing_stats:
            lines.append(f"- `{s}`")
        lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT.relative_to(BASE)}  ({total} entries)")
    for key, _p, title in TIER_DIRS:
        print(f"  {title}: {len(buckets.get(key, []))}")
    if orphan_dirs:
        print(f"  orphan dirs: {len(orphan_dirs)}")
    if missing_stats:
        print(f"  missing stats: {len(missing_stats)}")


if __name__ == "__main__":
    main()
